version: '3'
services:
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    network_mode: service:db
    depends_on:
      - db
      - mongo-backend
      - neo4j-backend

  mongo-backend:
    build:
      context: ./mongodb-backend
      dockerfile: Dockerfile
    volumes:
      - ./mongodb-backend/:/workspace:cached
    # command: sleep infinity
    network_mode: service:db
    depends_on:
      - db 
  
  neo4j-backend:
    build:
      context: ./neo4j-backend
      dockerfile: Dockerfile
    network_mode: service:db
    depends_on:
      - db
      - mongo-backend

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017" # Expose DB port
      - "5173:5173"   # Expose vue-app port
      - "3000:3000"   # Expose mongo-backend port
      - "8080:8000"   # Expose neo4j-backend port for debugging

    environment:
     MONGO_INITDB_ROOT_USERNAME: 
     MONGO_INITDB_ROOT_PASSWORD: 
     MONGO_INITDB_DATABASE: COURSE_DB

volumes:
  mongodb-data:
